{% set name = "neutralNEMO" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/neutralnemo-{{ version }}.tar.gz
  sha256: c3c49c29da5527b5ea6f5d4f7b782eef8826a0e3a2feac296054266c93f61d9a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - neutralocean >=2.1.2

test:
  imports:
    - neutralNEMO
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A package to calculate approximate neutral surfaces with NEMO model output
  license: MIT
  license_file: LICENSE
  home: https://github.com/afstyles/neutralNEMO

extra:
  recipe-maintainers:
    - afstyles
